### ISSUE TITLE
Any Instructions?

### ISSUE THREAD

**Issue by corradomatt** [cssstats/gulp-cssstats#1]
This looks really cool...any instructions for use or best practice? Thanks!

**Comment by jxnblk** [comment]
Guess I forgot to write up documentation. Basically you give it a CSS file and it returns JSON in the same format as the core module https://github.com/jxnblk/css-statistics. You can also pass options to the [PostCSS](https://github.com/postcss/postcss) module that it uses.

**Comment by corradomatt** [comment]
Thanks @jxnblk - that's a big help. Cheers!
